version: "3"

services:

  backend:
    image: dawhost/marketplace:latest
    ports:
      - "8443:8443"
    networks:
      - marketplace-net
    depends_on:
      - database
    restart: always

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - marketplace-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always

networks:
  marketplace-net:
