version: "3"

services:

  backend:
    image: daw-team-11/marketplace
    ports:
      - "8443:8443"
    networks:
      - marketplace-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - marketplace-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace

networks:
  marketplace-net:
